"""Observability helpers for e-GP services."""

from .logging import (
    RESULT_FRAME_BEGIN,
    RESULT_FRAME_END,
    make_event,
    redact_preview,
    rotate_log_copytruncate,
    tail_bounded_preview,
)
from .metrics import (
    CONTENT_TYPE,
    EXPECTED_METRIC_NAMES,
    get_metrics_registry,
    initialize_metrics,
    instrument_fastapi_app,
    metric_names_for_validation,
    observe_api_request,
    observe_rate_limiter_wait,
    record_discovery_anomaly,
    record_discovery_header_signature_drift,
    record_discovery_keyword_scan,
    record_discovery_scan_summary,
    record_document_capture_attempt,
    record_document_upsert_conflict,
    record_egp_request,
    record_worker_job,
    render_prometheus_metrics,
)

__all__ = [
    "RESULT_FRAME_BEGIN",
    "RESULT_FRAME_END",
    "make_event",
    "redact_preview",
    "rotate_log_copytruncate",
    "tail_bounded_preview",
    "CONTENT_TYPE",
    "EXPECTED_METRIC_NAMES",
    "get_metrics_registry",
    "initialize_metrics",
    "instrument_fastapi_app",
    "metric_names_for_validation",
    "observe_api_request",
    "observe_rate_limiter_wait",
    "record_discovery_anomaly",
    "record_discovery_header_signature_drift",
    "record_discovery_keyword_scan",
    "record_discovery_scan_summary",
    "record_document_capture_attempt",
    "record_document_upsert_conflict",
    "record_egp_request",
    "record_worker_job",
    "render_prometheus_metrics",
]
