#!/bin/sh
set -eu

ORIGINAL_DATABASE_URL_SET="${DATABASE_URL+x}"
ORIGINAL_DATABASE_URL="${DATABASE_URL-}"
ORIGINAL_EGP_ARTIFACT_ROOT_SET="${EGP_ARTIFACT_ROOT+x}"
ORIGINAL_EGP_ARTIFACT_ROOT="${EGP_ARTIFACT_ROOT-}"
ORIGINAL_EGP_API_PORT_SET="${EGP_API_PORT+x}"
ORIGINAL_EGP_API_PORT="${EGP_API_PORT-}"
ORIGINAL_EGP_PAYMENT_CALLBACK_SECRET_SET="${EGP_PAYMENT_CALLBACK_SECRET+x}"
ORIGINAL_EGP_PAYMENT_CALLBACK_SECRET="${EGP_PAYMENT_CALLBACK_SECRET-}"
ORIGINAL_EGP_AUTH_REQUIRED_SET="${EGP_AUTH_REQUIRED+x}"
ORIGINAL_EGP_AUTH_REQUIRED="${EGP_AUTH_REQUIRED-}"
ORIGINAL_EGP_JWT_SECRET_SET="${EGP_JWT_SECRET+x}"
ORIGINAL_EGP_JWT_SECRET="${EGP_JWT_SECRET-}"
ORIGINAL_EGP_SESSION_COOKIE_SECURE_SET="${EGP_SESSION_COOKIE_SECURE+x}"
ORIGINAL_EGP_SESSION_COOKIE_SECURE="${EGP_SESSION_COOKIE_SECURE-}"
ORIGINAL_EGP_WEB_ALLOWED_ORIGINS_SET="${EGP_WEB_ALLOWED_ORIGINS+x}"
ORIGINAL_EGP_WEB_ALLOWED_ORIGINS="${EGP_WEB_ALLOWED_ORIGINS-}"
ORIGINAL_EGP_WEB_BASE_URL_SET="${EGP_WEB_BASE_URL+x}"
ORIGINAL_EGP_WEB_BASE_URL="${EGP_WEB_BASE_URL-}"
ORIGINAL_NEXT_PUBLIC_EGP_API_BASE_URL_SET="${NEXT_PUBLIC_EGP_API_BASE_URL+x}"
ORIGINAL_NEXT_PUBLIC_EGP_API_BASE_URL="${NEXT_PUBLIC_EGP_API_BASE_URL-}"
ORIGINAL_EGP_LOCAL_DEV_OWNER_EMAIL_SET="${EGP_LOCAL_DEV_OWNER_EMAIL+x}"
ORIGINAL_EGP_LOCAL_DEV_OWNER_EMAIL="${EGP_LOCAL_DEV_OWNER_EMAIL-}"
ORIGINAL_EGP_LOCAL_DEV_OWNER_PASSWORD_SET="${EGP_LOCAL_DEV_OWNER_PASSWORD+x}"
ORIGINAL_EGP_LOCAL_DEV_OWNER_PASSWORD="${EGP_LOCAL_DEV_OWNER_PASSWORD-}"
ORIGINAL_EGP_LOCAL_DEV_OWNER_NAME_SET="${EGP_LOCAL_DEV_OWNER_NAME+x}"
ORIGINAL_EGP_LOCAL_DEV_OWNER_NAME="${EGP_LOCAL_DEV_OWNER_NAME-}"
ORIGINAL_EGP_LOCAL_DEV_TENANT_NAME_SET="${EGP_LOCAL_DEV_TENANT_NAME+x}"
ORIGINAL_EGP_LOCAL_DEV_TENANT_NAME="${EGP_LOCAL_DEV_TENANT_NAME-}"
ORIGINAL_EGP_LOCAL_DEV_TENANT_SLUG_SET="${EGP_LOCAL_DEV_TENANT_SLUG+x}"
ORIGINAL_EGP_LOCAL_DEV_TENANT_SLUG="${EGP_LOCAL_DEV_TENANT_SLUG-}"
USE_ENV_LOCAL_RUNTIME="${EGP_DEV_USE_ENV_LOCAL_RUNTIME:-false}"

if [ -f ./.env.local ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env.local
  set +a
fi

if [ "$ORIGINAL_DATABASE_URL_SET" = "x" ]; then
  DATABASE_URL="$ORIGINAL_DATABASE_URL"
fi
if [ "$ORIGINAL_EGP_ARTIFACT_ROOT_SET" = "x" ]; then
  EGP_ARTIFACT_ROOT="$ORIGINAL_EGP_ARTIFACT_ROOT"
fi
if [ "$ORIGINAL_EGP_API_PORT_SET" = "x" ]; then
  EGP_API_PORT="$ORIGINAL_EGP_API_PORT"
fi
if [ "$ORIGINAL_EGP_PAYMENT_CALLBACK_SECRET_SET" = "x" ]; then
  EGP_PAYMENT_CALLBACK_SECRET="$ORIGINAL_EGP_PAYMENT_CALLBACK_SECRET"
fi
if [ "$ORIGINAL_EGP_AUTH_REQUIRED_SET" = "x" ]; then
  EGP_AUTH_REQUIRED="$ORIGINAL_EGP_AUTH_REQUIRED"
fi
if [ "$ORIGINAL_EGP_JWT_SECRET_SET" = "x" ]; then
  EGP_JWT_SECRET="$ORIGINAL_EGP_JWT_SECRET"
fi
if [ "$ORIGINAL_EGP_SESSION_COOKIE_SECURE_SET" = "x" ]; then
  EGP_SESSION_COOKIE_SECURE="$ORIGINAL_EGP_SESSION_COOKIE_SECURE"
fi
if [ "$ORIGINAL_EGP_WEB_ALLOWED_ORIGINS_SET" = "x" ]; then
  EGP_WEB_ALLOWED_ORIGINS="$ORIGINAL_EGP_WEB_ALLOWED_ORIGINS"
fi
if [ "$ORIGINAL_EGP_WEB_BASE_URL_SET" = "x" ]; then
  EGP_WEB_BASE_URL="$ORIGINAL_EGP_WEB_BASE_URL"
fi
if [ "$ORIGINAL_NEXT_PUBLIC_EGP_API_BASE_URL_SET" = "x" ]; then
  NEXT_PUBLIC_EGP_API_BASE_URL="$ORIGINAL_NEXT_PUBLIC_EGP_API_BASE_URL"
fi
if [ "$ORIGINAL_EGP_LOCAL_DEV_OWNER_EMAIL_SET" = "x" ]; then
  EGP_LOCAL_DEV_OWNER_EMAIL="$ORIGINAL_EGP_LOCAL_DEV_OWNER_EMAIL"
fi
if [ "$ORIGINAL_EGP_LOCAL_DEV_OWNER_PASSWORD_SET" = "x" ]; then
  EGP_LOCAL_DEV_OWNER_PASSWORD="$ORIGINAL_EGP_LOCAL_DEV_OWNER_PASSWORD"
fi
if [ "$ORIGINAL_EGP_LOCAL_DEV_OWNER_NAME_SET" = "x" ]; then
  EGP_LOCAL_DEV_OWNER_NAME="$ORIGINAL_EGP_LOCAL_DEV_OWNER_NAME"
fi
if [ "$ORIGINAL_EGP_LOCAL_DEV_TENANT_NAME_SET" = "x" ]; then
  EGP_LOCAL_DEV_TENANT_NAME="$ORIGINAL_EGP_LOCAL_DEV_TENANT_NAME"
fi
if [ "$ORIGINAL_EGP_LOCAL_DEV_TENANT_SLUG_SET" = "x" ]; then
  EGP_LOCAL_DEV_TENANT_SLUG="$ORIGINAL_EGP_LOCAL_DEV_TENANT_SLUG"
fi

if [ "$USE_ENV_LOCAL_RUNTIME" != "true" ]; then
  if [ "$ORIGINAL_DATABASE_URL_SET" = "x" ]; then
    :
  else
    DATABASE_URL=""
  fi
  if [ "$ORIGINAL_EGP_API_PORT_SET" = "x" ]; then
    :
  else
    EGP_API_PORT=""
  fi
  if [ "$ORIGINAL_NEXT_PUBLIC_EGP_API_BASE_URL_SET" = "x" ]; then
    :
  else
    NEXT_PUBLIC_EGP_API_BASE_URL=""
  fi
fi

if [ -z "${DATABASE_URL:-}" ]; then
  DATABASE_URL="$(
    ../../.venv/bin/python ../../scripts/local_postgres_dev.py ensure-ready --database-url-only
  )"
fi
REPO_ROOT="$(cd ../.. && pwd)"
EGP_ARTIFACT_ROOT="${EGP_ARTIFACT_ROOT:-$REPO_ROOT/.data/artifacts}"
EGP_API_PORT="${EGP_API_PORT:-8010}"
EGP_PAYMENT_CALLBACK_SECRET="${EGP_PAYMENT_CALLBACK_SECRET:-top-secret}"
EGP_AUTH_REQUIRED="${EGP_AUTH_REQUIRED:-false}"
EGP_JWT_SECRET="${EGP_JWT_SECRET:-dev-jwt-secret}"
EGP_SESSION_COOKIE_SECURE="${EGP_SESSION_COOKIE_SECURE:-false}"
EGP_WEB_ALLOWED_ORIGINS="${EGP_WEB_ALLOWED_ORIGINS:-http://127.0.0.1:3002,http://localhost:3002}"
EGP_WEB_BASE_URL="${EGP_WEB_BASE_URL:-http://127.0.0.1:3002}"
NEXT_PUBLIC_EGP_API_BASE_URL="${NEXT_PUBLIC_EGP_API_BASE_URL:-http://127.0.0.1:${EGP_API_PORT}}"
EGP_LOCAL_DEV_OWNER_EMAIL="${EGP_LOCAL_DEV_OWNER_EMAIL:-owner@local-dev.example}"
EGP_LOCAL_DEV_OWNER_PASSWORD="${EGP_LOCAL_DEV_OWNER_PASSWORD:-DevPassword123!}"
EGP_LOCAL_DEV_OWNER_NAME="${EGP_LOCAL_DEV_OWNER_NAME:-Local Dev Owner}"
EGP_LOCAL_DEV_TENANT_NAME="${EGP_LOCAL_DEV_TENANT_NAME:-Local Dev Workspace}"
EGP_LOCAL_DEV_TENANT_SLUG="${EGP_LOCAL_DEV_TENANT_SLUG:-local-dev}"

export DATABASE_URL
export EGP_ARTIFACT_ROOT
export EGP_API_PORT
export EGP_PAYMENT_CALLBACK_SECRET
export EGP_AUTH_REQUIRED
export EGP_JWT_SECRET
export EGP_SESSION_COOKIE_SECURE
export EGP_WEB_ALLOWED_ORIGINS
export EGP_WEB_BASE_URL
export NEXT_PUBLIC_EGP_API_BASE_URL
export EGP_LOCAL_DEV_OWNER_EMAIL
export EGP_LOCAL_DEV_OWNER_PASSWORD
export EGP_LOCAL_DEV_OWNER_NAME
export EGP_LOCAL_DEV_TENANT_NAME
export EGP_LOCAL_DEV_TENANT_SLUG

case "$DATABASE_URL" in
  postgresql://*|postgresql+psycopg://*)
    ../../.venv/bin/python -m egp_db.migration_runner \
      --database-url "$DATABASE_URL" \
      --migrations-dir ../../packages/db/src/migrations
    ../../.venv/bin/python ../../scripts/seed_manual_test_user.py \
      --database-url "$DATABASE_URL" >/dev/null
    ;;
  sqlite://*|sqlite+pysqlite://*)
    ../../.venv/bin/python ../../scripts/local_dev_auth_seed.py ensure-owner \
      --database-url "$DATABASE_URL" \
      --tenant-name "$EGP_LOCAL_DEV_TENANT_NAME" \
      --tenant-slug "$EGP_LOCAL_DEV_TENANT_SLUG" \
      --email "$EGP_LOCAL_DEV_OWNER_EMAIL" \
      --password "$EGP_LOCAL_DEV_OWNER_PASSWORD" \
      --full-name "$EGP_LOCAL_DEV_OWNER_NAME" >/dev/null
    ;;
esac

../../.venv/bin/uvicorn src.main:app \
  --app-dir ../api \
  --reload \
  --reload-dir ../api/src \
  --reload-dir ../../packages \
  --host 127.0.0.1 \
  --port "$EGP_API_PORT" &
api_pid=$!

cleanup() {
  kill "$api_pid" 2>/dev/null || true
  wait "$api_pid" 2>/dev/null || true
}

trap cleanup EXIT INT TERM

./scripts/dev-web.sh --hostname 127.0.0.1 --port 3002
